package com.webcrawler.dao;
// Generated Jun 15, 2017 8:33:41 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * RunIdentTbl generated by hbm2java
 */
public class AuthTbl implements java.io.Serializable {

	private Integer id;
	private String authOppNav;
	private String authId;
	private String authPass;
	private String authSignoutNav;

	public AuthTbl() {
	}

	public AuthTbl(String authOppNav, String authId, String authPass, String authSignoutNav) {
		this.setAuthOppNav(authOppNav);
		this.setAuthId(authId);
		this.setAuthPass(authPass);
		this.setAuthSignoutNav(authSignoutNav);
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAuthOppNav() {
		return authOppNav;
	}

	public void setAuthOppNav(String authOppNav) {
		this.authOppNav = authOppNav;
	}

	public String getAuthId() {
		return authId;
	}

	public void setAuthId(String authId) {
		this.authId = authId;
	}

	public String getAuthPass() {
		return authPass;
	}

	public void setAuthPass(String authPass) {
		this.authPass = authPass;
	}

	public String getAuthSignoutNav() {
		return authSignoutNav;
	}

	public void setAuthSignoutNav(String authSignoutNav) {
		this.authSignoutNav = authSignoutNav;
	}

}
