package com.webcrawler.dao;
// Generated Sep 12, 2017 10:44:29 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * CredsTbl generated by hbm2java
 */
public class CredsTbl implements java.io.Serializable {

	private Integer id;
	private RunIdentTbl runIdentTbl;
	private String username;
	private String password;
	private String usernameVariable;
	private String passwordVariable;

	public CredsTbl() {
	}

	public CredsTbl(RunIdentTbl runIdentTbl, String username, String password) {
		this.runIdentTbl = runIdentTbl;
		this.username = username;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RunIdentTbl getRunIdentTbl() {
		return this.runIdentTbl;
	}

	public void setRunIdentTbl(RunIdentTbl runIdentTbl) {
		this.runIdentTbl = runIdentTbl;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsernameVariable() {
		return usernameVariable;
	}

	public void setUsernameVariable(String usernameVariable) {
		this.usernameVariable = usernameVariable;
	}

	public String getPasswordVariable() {
		return passwordVariable;
	}

	public void setPasswordVariable(String passwordVariable) {
		this.passwordVariable = passwordVariable;
	}

}
