package com.webcrawler.dao;
// Generated Jun 15, 2017 8:33:41 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * RunIdentTbl generated by hbm2java
 */
public class EncoderTbl implements java.io.Serializable {

	private Integer id;
	private String character;
	private String encoded;

	public EncoderTbl() {
	}

	public EncoderTbl(String character, String encoded) {
		this.setCharacter(character);
		this.setEncoded(encoded);
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCharacter() {
		return character;
	}

	public void setCharacter(String character) {
		this.character = character;
	}

	public String getEncoded() {
		return encoded;
	}

	public void setEncoded(String encoded) {
		this.encoded = encoded;
	}

}
