package com.webcrawler.dao;
// Generated Sep 12, 2017 10:44:29 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * HeaderCorrelationTbl generated by hbm2java
 */
public class HeaderCorrelationTbl implements java.io.Serializable {

	private Integer id;
	private RunIdentTbl runIdentTbl;
	private String foundHeaderName;
	private String foundHeaderValue;
	private String variable;
	private String corrRegex;

	public HeaderCorrelationTbl() {
	}

	public HeaderCorrelationTbl(RunIdentTbl runIdentTbl, String foundHeaderName, String foundHeaderValue, String variable, String corrRegex) {
		this.runIdentTbl = runIdentTbl;
		this.foundHeaderName = foundHeaderName;
		this.foundHeaderValue = foundHeaderValue;
		this.variable = variable;
		this.corrRegex = corrRegex;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RunIdentTbl getRunIdentTbl() {
		return this.runIdentTbl;
	}

	public void setRunIdentTbl(RunIdentTbl runIdentTbl) {
		this.runIdentTbl = runIdentTbl;
	}

	public String getFoundHeaderName() {
		return this.foundHeaderName;
	}

	public void setFoundHeaderName(String foundHeaderName) {
		this.foundHeaderName = foundHeaderName;
	}

	public String getFoundHeaderValue() {
		return this.foundHeaderValue;
	}

	public void setFoundHeaderValue(String foundHeaderValue) {
		this.foundHeaderValue = foundHeaderValue;
	}

	public String getVariable() {
		return this.variable;
	}

	public void setVariable(String variable) {
		this.variable = variable;
	}

	public String getCorrRegex() {
		return this.corrRegex;
	}

	public void setCorrRegex(String corrRegex) {
		this.corrRegex = corrRegex;
	}

}
