package com.webcrawler.dao;
// Generated Jun 13, 2017 8:59:00 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * JmeterTransControllerTbl generated by hbm2java
 */
public class JmeterTransControllerTbl implements java.io.Serializable {

	private Integer id;
	private RequestResponseTbl requestResponseTbl;
	private String transContSec;
	private byte[] screenShot;

	public JmeterTransControllerTbl() {
	}

	public JmeterTransControllerTbl(RequestResponseTbl requestResponseTbl, String transContSec, byte[] screenShot) {
		this.requestResponseTbl = requestResponseTbl;
		this.transContSec = transContSec;
		this.screenShot = screenShot;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RequestResponseTbl getRequestResponseTbl() {
		return this.requestResponseTbl;
	}

	public void setRequestResponseTbl(RequestResponseTbl requestResponseTbl) {
		this.requestResponseTbl = requestResponseTbl;
	}

	public String getTransContSec() {
		return this.transContSec;
	}

	public void setTransContSec(String transContSec) {
		this.transContSec = transContSec;
	}

	public byte[] getScreenShot() {
		return this.screenShot;
	}

	public void setScreenShot(byte[] screenShot) {
		this.screenShot = screenShot;
	}

}
