package com.webcrawler.dao;
// Generated Sep 12, 2017 10:44:29 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * KnownExtractorsTbl generated by hbm2java
 */
public class KnownExtractorsTbl implements java.io.Serializable {

	private Integer id;
	private String knownValue;
	private String extractor;

	public KnownExtractorsTbl() {
	}

	public KnownExtractorsTbl(String knownValue, String extractor) {
		this.setKnownValue(knownValue);
		this.setExtractor(extractor);
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKnownValue() {
		return knownValue;
	}

	public void setKnownValue(String knownValue) {
		this.knownValue = knownValue;
	}

	public String getExtractor() {
		return extractor;
	}

	public void setExtractor(String extractor) {
		this.extractor = extractor;
	}

}
