package com.webcrawler.dao;
// Generated Sep 12, 2017 10:44:29 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * KnownExtractorsTbl generated by hbm2java
 */
public class PageCategoryTbl implements java.io.Serializable {

	private Integer id;
	private String keyword;
	private String category;

	public PageCategoryTbl() {
	}

	public PageCategoryTbl(String keyword, String category) {
		this.setKeyword(keyword);
		this.setCategory(category);
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKeyword() {
		return keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

}
