package com.webcrawler.dao;
// Generated May 11, 2017 2:36:17 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * RequestResponseTbl generated by hbm2java
 */
public class RequestResponseTbl implements java.io.Serializable {

	private Integer id;
	private RunIdentTbl runIdentTbl;
	private String responseBody;
	private String fromPageTitle;
	private String fromPageUrl;
	private String toPageTitle;
	private String toPageUrl;
	private Integer pageTransitionIterationNumber;
	private String requestHeader;
	private String responseHeader;

	public RequestResponseTbl() {
	}

	public RequestResponseTbl(RunIdentTbl runIdentTbl, String responseBody, String fromPageTitle, String fromPageUrl, String toPageTitle,
			String toPageUrl, Integer pageTransitionIterationNumber, String requestHeader, String responseHeader) {
		this.runIdentTbl = runIdentTbl;
		this.responseBody = responseBody;
		this.fromPageTitle = fromPageTitle;
		this.fromPageUrl = fromPageUrl;
		this.toPageTitle = toPageTitle;
		this.toPageUrl = toPageUrl;
		this.pageTransitionIterationNumber = pageTransitionIterationNumber;
		this.requestHeader = requestHeader;
		this.responseHeader = responseHeader;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RunIdentTbl getRunIdentTbl() {
		return this.runIdentTbl;
	}

	public void setRunIdentTbl(RunIdentTbl runIdentTbl) {
		this.runIdentTbl = runIdentTbl;
	}

	public String getResponseBody() {
		return this.responseBody;
	}

	public void setResponseBody(String responseBody) {
		this.responseBody = responseBody;
	}

	public String getFromPageTitle() {
		return this.fromPageTitle;
	}

	public void setFromPageTitle(String fromPageTitle) {
		this.fromPageTitle = fromPageTitle;
	}

	public String getFromPageUrl() {
		return this.fromPageUrl;
	}

	public void setFromPageUrl(String fromPageUrl) {
		this.fromPageUrl = fromPageUrl;
	}

	public String getToPageTitle() {
		return this.toPageTitle;
	}

	public void setToPageTitle(String toPageTitle) {
		this.toPageTitle = toPageTitle;
	}

	public String getToPageUrl() {
		return this.toPageUrl;
	}

	public void setToPageUrl(String toPageUrl) {
		this.toPageUrl = toPageUrl;
	}

	public Integer getPageTransitionIterationNumber() {
		return this.pageTransitionIterationNumber;
	}

	public void setPageTransitionIterationNumber(Integer pageTransitionIterationNumber) {
		this.pageTransitionIterationNumber = pageTransitionIterationNumber;
	}

	public String getRequestHeader() {
		return this.requestHeader;
	}

	public void setRequestHeader(String requestHeader) {
		this.requestHeader = requestHeader;
	}

	public String getResponseHeader() {
		return this.responseHeader;
	}

	public void setResponseHeader(String responseHeader) {
		this.responseHeader = responseHeader;
	}

}
