package com.webcrawler.dao;
// Generated Jun 15, 2017 8:33:41 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * RequestResponseTbl generated by hbm2java
 */
public class RequestResponseTbl implements java.io.Serializable {

	private Integer id;
	private RunIdentTbl runIdentTbl;
	private String responseBody;
	private String fromPageTitle;
	private String fromPageUrl;
	private Integer toPageLevel;
	private Integer authenticated;
	private String toPageTitle;
	private String toPageUrl;
	private Integer pageTransitionIterationNumber;
	private String requestHeader;
	private String requestParameters;
	private String responseHeader;
	private Set jmeterTransControllerTbls = new HashSet(0);

	public RequestResponseTbl() {
	}

	public RequestResponseTbl(RunIdentTbl runIdentTbl, String responseBody, String fromPageTitle, String fromPageUrl, Integer toPageLevel, Integer authenticated,
			String toPageTitle, String toPageUrl, Integer pageTransitionIterationNumber, String requestHeader, String requestParameters, String responseHeader,
			Set jmeterTransControllerTbls) {
		this.runIdentTbl = runIdentTbl;
		this.responseBody = responseBody;
		this.fromPageTitle = fromPageTitle;
		this.fromPageUrl = fromPageUrl;
		this.toPageLevel = toPageLevel;
		this.setAuthenticated(authenticated);
		this.toPageTitle = toPageTitle;
		this.toPageUrl = toPageUrl;
		this.pageTransitionIterationNumber = pageTransitionIterationNumber;
		this.requestHeader = requestHeader;
		this.setRequestParameters(requestParameters);
		this.responseHeader = responseHeader;
		this.jmeterTransControllerTbls = jmeterTransControllerTbls;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RunIdentTbl getRunIdentTbl() {
		return this.runIdentTbl;
	}

	public void setRunIdentTbl(RunIdentTbl runIdentTbl) {
		this.runIdentTbl = runIdentTbl;
	}

	public String getResponseBody() {
		return this.responseBody;
	}

	public void setResponseBody(String responseBody) {
		this.responseBody = responseBody;
	}

	public String getFromPageTitle() {
		return this.fromPageTitle;
	}

	public void setFromPageTitle(String fromPageTitle) {
		this.fromPageTitle = fromPageTitle;
	}

	public String getFromPageUrl() {
		return this.fromPageUrl;
	}

	public void setFromPageUrl(String fromPageUrl) {
		this.fromPageUrl = fromPageUrl;
	}

	public Integer getToPageLevel() {
		return this.toPageLevel;
	}

	public void setToPageLevel(Integer toPageLevel) {
		this.toPageLevel = toPageLevel;
	}

	public Integer getAuthenticated() {
		return authenticated;
	}

	public void setAuthenticated(Integer authenticated) {
		this.authenticated = authenticated;
	}

	public String getToPageTitle() {
		return this.toPageTitle;
	}

	public void setToPageTitle(String toPageTitle) {
		this.toPageTitle = toPageTitle;
	}

	public String getToPageUrl() {
		return this.toPageUrl;
	}

	public void setToPageUrl(String toPageUrl) {
		this.toPageUrl = toPageUrl;
	}

	public Integer getPageTransitionIterationNumber() {
		return this.pageTransitionIterationNumber;
	}

	public void setPageTransitionIterationNumber(Integer pageTransitionIterationNumber) {
		this.pageTransitionIterationNumber = pageTransitionIterationNumber;
	}

	public String getRequestHeader() {
		return this.requestHeader;
	}

	public void setRequestHeader(String requestHeader) {
		this.requestHeader = requestHeader;
	}

	public String getRequestParameters() {
		return requestParameters;
	}

	public void setRequestParameters(String requestParameters) {
		this.requestParameters = requestParameters;
	}

	public String getResponseHeader() {
		return this.responseHeader;
	}

	public void setResponseHeader(String responseHeader) {
		this.responseHeader = responseHeader;
	}

	public Set getJmeterTransControllerTbls() {
		return this.jmeterTransControllerTbls;
	}

	public void setJmeterTransControllerTbls(Set jmeterTransControllerTbls) {
		this.jmeterTransControllerTbls = jmeterTransControllerTbls;
	}

}
