package com.webcrawler.dao;
// Generated Jun 15, 2017 8:33:41 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * RunIdentTbl generated by hbm2java
 */
public class RunIdentTbl implements java.io.Serializable {

	private Integer id;
	private String runIdentifier;
	private String baseUrl;
	private Boolean cleansed;
	private Integer percent;
	private String authFileLoc;
	private Set requestResponseTbls = new HashSet(0);

	public RunIdentTbl() {
	}

	public RunIdentTbl(String runIdentifier, String baseUrl, Boolean cleansed, Integer percent, String authFileLoc, Set requestResponseTbls) {
		this.runIdentifier = runIdentifier;
		this.baseUrl = baseUrl;
		this.cleansed = cleansed;
		this.percent = percent;
		this.requestResponseTbls = requestResponseTbls;
		this.setAuthFileLoc(authFileLoc);
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRunIdentifier() {
		return this.runIdentifier;
	}

	public void setRunIdentifier(String runIdentifier) {
		this.runIdentifier = runIdentifier;
	}

	public String getBaseUrl() {
		return this.baseUrl;
	}

	public void setBaseUrl(String baseUrl) {
		this.baseUrl = baseUrl;
	}

	public Boolean getCleansed() {
		return this.cleansed;
	}

	public void setCleansed(Boolean cleansed) {
		this.cleansed = cleansed;
	}

	public Integer getPercent() {
		return this.percent;
	}

	public void setPercent(Integer percent) {
		this.percent = percent;
	}

	public String getAuthFileLoc() {
		return authFileLoc;
	}

	public void setAuthFileLoc(String authFileLoc) {
		this.authFileLoc = authFileLoc;
	}

	public Set getRequestResponseTbls() {
		return this.requestResponseTbls;
	}

	public void setRequestResponseTbls(Set requestResponseTbls) {
		this.requestResponseTbls = requestResponseTbls;
	}

}
