package com.webcrawler.dao;
// Generated May 11, 2017 2:36:17 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * RunIdentTbl generated by hbm2java
 */
public class RunIdentTbl implements java.io.Serializable {

	private Integer id;
	private String runIdentifier;
	private Set requestResponseTbls = new HashSet(0);

	public RunIdentTbl() {
	}

	public RunIdentTbl(String runIdentifier, Set requestResponseTbls) {
		this.runIdentifier = runIdentifier;
		this.requestResponseTbls = requestResponseTbls;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRunIdentifier() {
		return this.runIdentifier;
	}

	public void setRunIdentifier(String runIdentifier) {
		this.runIdentifier = runIdentifier;
	}

	public Set getRequestResponseTbls() {
		return this.requestResponseTbls;
	}

	public void setRequestResponseTbls(Set requestResponseTbls) {
		this.requestResponseTbls = requestResponseTbls;
	}

}
